_BASE_: "Base-DefGird-MRCNN-FPN.yaml"
MODEL:
  WEIGHTS: "defgrid_dconv.pth"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT : 5
  MASK_ON: True
  ANCHOR_GENERATOR:
    SIZES: [[64], [128], [256], [512],[1024]]  # One size for each in feature map
    ASPECT_RATIOS: [1,3,10]
  RESNETS:
    DEPTH: 50
    DEFORM_ON_PER_STAGE: [False, True, True, True] # on Res3, Res4, Res5
    DEFORM_MODULATED: False
  DEFGRID_MASK_HEAD:
    W_AREA: 0.05
    W_LAPLACIAN: 0.05
  ROI_HEADS:
    NUM_CLASSES: 1
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.02
  STEPS: (8000, 12000)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 1000
INPUT:
  MIN_SIZE_TRAIN: (800,)
DATASETS:
  TRAIN: ("indiscapes_train",)
  TEST: ("indiscapes_val",)
OUTPUT_DIR: "outputs/Palmira_pb"
VIS_PERIOD: 500
TEST:
  EVAL_PERIOD: 500